### ISSUE TITLE
Can't handle filenames with spaces

### ISSUE THREAD

**Issue by DougReeder** [web-alchemy/eleventy-plugin-content-dates#1]
For files with names like `JavaScript Service Worker Design Patterns.md`, it throws 

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Command failed: git --no-pager log -n 1 --format="%ci" ./content/presentations/JavaScript Service Worker Design Patterns.md
[11ty] fatal: ambiguous argument './content/presentations/JavaScript': unknown revision or path not in the working tree.

Platform: MacOS Sonoma 14.5

**Comment by DougReeder** [comment]
What worked for me was using this filter, based on your code:
```
const { execFile } = require('node:child_process');
const util = require('node:util');


module.exports = async function(filePath) {
	const args = ['--no-pager', 'log', '-n', '1', '--format="%ci"', filePath];
	const { stdout } = await util.promisify(execFile)('git', args, { encoding: 'utf-8' });

	return new Date(stdout);
};
```

Maybe you could tweak the code so the file path is passed as one element of the args array.

**Comment by monochromer** [comment]
You can test bug fix now:
```sh
npm add https://github.com/web-alchemy/eleventy-plugin-content-dates.git#fix-git-args
```

Later i will publish new patch version.

**Comment by monochromer** [comment]
The patch has been published.

**Comment by DougReeder** [comment]
Thanks much, it works great!

It might be helpful, in the docs, to note that variable `foo` set in *.11tydata.js files will show up as `page.data.foo` in template files.  Experienced users know that, but it's not obvious.
